name: FinalProjectBackend2
dependencies:
    - python=3.12.4
    - pip=24.0
    - pip:
      - django==5.0.7
      - djangorestframework==3.15.2
      - djangorestframework-simplejwt==5.3.1
      - drf-yasg==1.21.7
      - django-dotenv==1.4.2
      - django-storages==1.14.4   # Used to connect to deployed media files storage
      - django-cors-headers==4.4.0  # Used to allow connection between frontend to backend
      - dj-database-url==2.2.0 # Used to configure Postgres via Heroku URL
      - gunicorn==22.0.0         # Python web server to run application
      - markdown==3.6  # Used by drf-yasg for automatic api documentation
      - pillow==10.4.0            # Python image library - needed when handling images
      - whitenoise==6.7.0         # Library to serve static files in deployment mode
      - boto3==1.34.144  # AWS SDK - allows application to interact with things like AWS S3 or DO Spaces
      - psycopg2-binary==2.9.9