# Generated by Django 5.0.7 on 2024-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDt', models.DateTimeField()),
                ('endDt', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick Leave')], default='vacation', max_length=11)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=11)),
                ('durationWorkHours', models.FloatField(default=-1.0)),
                ('durationWorkTimeFormatted', models.CharField(default='-1d_-1h_-1m', max_length=30)),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
                ('dtUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
