# Generated by Django 5.0.7 on 2024-07-31 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDependentVar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('variable', models.CharField(choices=[('nr_tot_vacation_days', 'Total Vacation Days'), ('pensum_perc', 'Pensum %'), ('maternity_leave', 'Maternity Leave'), ('nr_working_hours_per_week', 'Working Hours per Week'), ('nr_working_hours_per_day_at100PercPensum', 'Nr of Working Hours per Day at 100% pensum to compute conversion of hours into days'), ('day_Monday_startTime', 'Monday Start Time of Work (HH:MM)'), ('day_Monday_endTime', 'Monday End Time of Work (HH:MM)'), ('day_Tuesday_startTime', 'Tuesday Start Time of Work (HH:MM)'), ('day_Tuesday_endTime', 'Tuesday End Time of Work (HH:MM)'), ('day_Wednesday_startTime', 'Wednesday Start Time of Work (HH:MM)'), ('day_Wednesday_endTime', 'Wednesday End Time of Work (HH:MM)'), ('day_Thursday_startTime', 'Thursday Start Time of Work (HH:MM)'), ('day_Thursday_endTime', 'Thursday End Time of Work (HH:MM)'), ('day_Friday_startTime', 'Friday Start Time of Work (HH:MM)'), ('day_Friday_endTime', 'Friday End Time of Work (HH:MM)'), ('day_Saturday_startTime', 'Saturday Start Time of Work (HH:MM)'), ('day_Saturday_endTime', 'Saturday End Time of Work (HH:MM)'), ('day_Sunday_startTime', 'Sunday Start Time of Work (HH:MM)'), ('day_Sunday_endTime', 'Sunday End Time of Work (HH:MM)')], default='nr_tot_vacation_days', max_length=50)),
                ('value', models.CharField(max_length=40)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeDepVars', to='userProfile.userprofile')),
            ],
        ),
    ]
